New main with all the monitoring on
Azure-Samples/java-native-telemetry pull request #52
Opened 2024-05-23 10:16 UTC by brunobat

2024-05-23 13:22 UTC, jeanbisutti approved these changes

2024-05-23 13:22 UTC, jeanbisutti commented on code/spring-boot-telemetry/src/main/resources/application.properties
>  spring.jpa.hibernate.ddl-auto=update
To have the same configuration for Quarkus and Spring:

```suggestion
spring.jpa.hibernate.ddl-auto=drop-and-create
```

2024-05-23 13:22 UTC, jeanbisutti commented on code/spring-boot-telemetry/src/main/resources/application.properties
> +applicationinsights.connection.string=InstrumentationKey=yourInsightsKey
To have the same thing for Spring and Quarkus:

```suggestion
applicationinsights.connection.string=InstrumentationKey=00000000-0000-0000-0000-000000000000
```

2024-06-06 15:05 UTC, SandraAhlgrimm commented on code/quarkus-telemetry/quarkus-telemetry-superhero/docker-compose.yml
> -    image: localhost/quarkus-telemetry-superhero:latest
I'd keep localhost here as we can't rely on the correct version in the registry

2024-06-06 15:37 UTC, SandraAhlgrimm commented on .github/workflows/quarkus-native-monitoring-AutoDeployTrigger-cd1d418e-9e7d-4855-bcfa-dc4948f26827.yml
> +          environmentVariables: 'QUARKUS_DATASOURCE_JDBC_URL=${{ secrets.DATABASE_URL_SUPER }} QUARKUS_DATASOURCE_USERNAME=${{ secrets.DATABASE_USERNAME }} QUARKUS_DATASOURCE_PASSWORD=${{ secrets.DAT
let's rename to AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING for ease

2024-06-06 15:40 UTC, SandraAhlgrimm commented on code/spring-boot-telemetry/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=drop-and-create
remove doubled spring.jpa.hibernate.ddl-auto

2024-06-06 15:41 UTC, SandraAhlgrimm requested changes
small adjustments needed as commented

2024-06-08 18:36 UTC, SandraAhlgrimm approved these changes

2024-06-08 18:39 UTC, merged